module.exports = {
    setacCarrosel: "//i[contains(@class,'icon icon-right-chevron')]",
    bannerCarrosel: "//img[contains(@class,'slide__image swiper-lazy swiper-lazy-loaded')]",
    midiaCarrosel: "//a[@class='link-video'][contains(.,'Clique aqui para mais detalhes')]",
    cardOfertas: "//img[contains(@alt,'Z4 2022')]",
    titleCard:"//div[@class='card-land__title'][contains(.,'Z4 2022')]",
    imagemMiniatura: "//img[contains(@alt,'Z4 2022')]",
    textoOferta: "(//div[contains(.,'Entrada de R$ 55.000,00')])[8]",
    btn_saibaMais: "(//button[contains(.,'Saiba Mais')])[1]",
    btnOrdenar: "(//div[contains(.,'sDrive30i M Sport')])[15]",
    selecaoCarro: "(//div[@class='choices__item choices__item--selectable'][contains(.,'sDrive30i M Sport')])[1]",
    CarroSelecionado: "(//div[@class='choices__item choices__item--selectable'][contains(.,'sDrive30i M Sport')])[1]",
    formBTNOrdenar: "(//div[@class='choices__list choices__list--single'][contains(.,'sDrive30i M Sport')])[2]",
    precoCarro: "(//div[contains(.,'Entrada de R$ 55.000,00')])[12]",
    selecaoForm: "(//div[contains(.,'sDrive30i M Sport')])[27]",
    formMarcaSelecionada: "(//div[contains(.,'sDrive30i M Sport')])[27]",
    formName: "//input[@placeholder='Nome']",
    formEmail: "//input[@placeholder='E-mail']",
    formTelefone: "//input[contains(@placeholder,'Telefone/Whatsapp')]",
    formCPF: "(//input[contains(@type,'text')])[4]",
    BTN_mensagem: "//div[@data-parent='#header-card-phones'][contains(.,'AutoDealer São Paulo')]",
    BTN_menuSemiNovos: "(//li[contains(.,'Seminovos:(11) 2020-1010')])[2]",
    BTN_novos: "(//li[contains(.,'Novos:(11) 2020-1010')])[2]",
    BTN_vendas: "(//li[contains(.,'Novos:(11) 2020-1010')])[2]",
    successfully: "(//div[contains(.,'Solicitação realizada com sucesso!')])[10]",
    rodape: "//a[@class='nav-vertical__link active'][contains(.,'AutoDealer São Paulo')]",
    endereco: "(//h2[contains(.,'Endereço:')])[1]",
    rua: "//p[contains(.,'Rua vergueiro , 2253 - Trend Paulista, Sala 115 - Vila Mariana - São Paulo-SP')]",
    atendimento: "(//h2[@class='footer-land-units__title'][contains(.,'Horários de Funcionamento:')])[1]",
    showroom: "(//li[contains(.,'Showroom:  Segunda a Sexta das 8h às 18h. Sábado das 8h às 12h.')])[1]",
    oficina: "(//li[contains(.,'Oficina:  Segunda a Sexta das 8h às 17h. Sábado das 8h às 12h.')])[1]",
    pos_venda: "(//li[contains(.,'Pós-Venda:  Segunda a sexta das 8h às 12h')])[1]",
    filialNatal: "//a[@class='nav-vertical__link active'][contains(.,'AutoDealer Natal')]",
    enderecoNatal: "(//h2[@class='footer-land-units__title'][contains(.,'Endereço:')])[2]",
    ruaFilialNatal: "//p[contains(.,'Av. Amintas Barros, 3700 - Torre Business - Sala 2506 - Lagoa Nova - Natal-RN')]",
    atendimentoFilialNatal: "(//h2[contains(.,'Horários de Funcionamento:')])[2]",
    showroomFilialNatal: "(//li[contains(.,'Showroom:  Segunda a Sexta das 8h às 17h. Sábado das 8h às 10h.')])[1]",
    oficinaFilialNatal: "(//li[contains(.,'Oficina:  Segunda a Sexta das 8h às 18h. Sábado das 8h às 12h.')])[1]",
    cnpjSP: "//div[@class='footer-land__info-item'][contains(.,'CNPJ: 22.588.947/0001-06')]",
    enderecoMatrizSP: "//div[@class='footer-land__info-item'][contains(.,'Endereço Matriz: Av. Amintas Barros, 3700, Torre Business, Sala 2503 - Lagoa Nova, Natal - RN, CEP: 59075-250')]",
    razaoSocialSP: "//div[@class='footer-land__info-item'][contains(.,'Razão Social: AUTO FORCE PLATAFORMA DE MARKETING DIGITAL LTDA')]",
    cnpjNatal: "//div[@class='footer-land__info-item'][contains(.,'CNPJ: 22.588.947/0001-06')]",
    enderecoFilialNatal: "//div[@class='footer-land__info-item'][contains(.,'Endereço Matriz: Av. Amintas Barros, 3700, Torre Business, Sala 2503 - Lagoa Nova, Natal - RN, CEP: 59075-250')]",
    razaoSocialNatal: "//div[@class='footer-land__info-item'][contains(.,'Razão Social: AUTO FORCE PLATAFORMA DE MARKETING DIGITAL LTDA')]"
} 